apiVersion: v1
kind: Template
metadata:
  name: project-request
  namespace: openshift
objects:
- apiVersion: v1
  displayName: ${PROJECT_DISPLAYNAME}
  kind: Project
  metadata:
    annotations:
      description: ${PROJECT_DESCRIPTION}
      displayName: ${PROJECT_DISPLAYNAME}
      openshift.io/node-selector: region=primary   
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admins
    namespace: ${PROJECT_NAME}
  roleRef:
    name: admin
  userNames:
  - ${PROJECT_ADMIN_USER}
parameters:
- name: PROJECT_NAME 
- name: PROJECT_DISPLAYNAME 
- name: PROJECT_DESCRIPTION 
- name: PROJECT_ADMIN_USER
